### ISSUE TITLE
Error - events.js:187 - Unhandled 'error' event

### ISSUE THREAD

**Issue by bobbywhitesfdc** [scolladon/sfdc-git-package#13]
sgp -f fe6df99ec3e030c73e20cc620144c020b76d55b4 -o ./output
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn git',
  path: 'git',
  spawnargs: [
    'diff',
    '--name-status',
    'fe6df99ec3e030c73e20cc620144c020b76d55b4',
    'HEAD'
  ]
}

**Comment by bobbywhitesfdc** [comment]
It appears to me that spg cannot launch git.  Not sure what info you might need from me to debug this!

**Comment by scolladon** [comment]
The repo should be specified.
Else the default value will be taken (./repo)

**Comment by bobbywhitesfdc** [comment]
I’m not following your response well.  How would I specify the repo?  I’m running the command from the root directory of the git repo ( and my project).

**Comment by scolladon** [comment]
You want to provide the --repo parameter or shorter version : -r  to the cli.
In your case as you are in the repo when executing the command line, you just need to provide "-r ." parameter
