### ISSUE TITLE
The parsing of *.object files.

### ISSUE THREAD

**Issue by adamantine-dev** [scolladon/sfdc-git-package#5]
Hi Sebastien.

As I know, your tool [sfdc-generate-package](https://github.com/scolladon/sfdc-generate-package) do the parsing of *.object files. I mean in a result package.xml file I've seen _ActionOverride_, _CustomField_, _ListView_, _RecordType_, etc. types of metadata. All to those store in the *.object files.

I tried to use [sfdc-git-package](https://github.com/scolladon/sfdc-git-package) and I faced the problem: in the package.xml file I don't see the metadata type sections stored in the *.object files.

Does exist any flag to do this type of parsing? Or it's a missing functionality?

Thanks! :)

**Comment by adamantine-dev** [comment]
I've noticed that your metadata.js files are different in two packages:

[sfdc-git-package](https://github.com/scolladon/sfdc-git-package/blob/1e121ea39c75faa47372a9ecfc677302e3e5bc87/lib/utils/metadata.js#L44)

[sfdc-generate-package](https://github.com/scolladon/sfdc-generate-package/blob/5303bf0295c91befc1fa2d34fda228366a974b2b/lib/utils/metadata.js#L68)

As I understood you have slightly different the parsing functionality. 
Looks like it should work in both cases, but it doesn't.

Or do I do something wrong? :)

**Comment by scolladon** [comment]
Hello, you are perfectly right !
sfdc-git-package is different than sfdc-generate-package.

sfdc-generate-package parse the content of src and create the package.xml
sfdc-git-package parse the git diff from two commit in the src and then create the package.xml. When there is a diff into an object file that concerns a custom field (Create/Update/Delete operation) the command line do not insight deep enough to deduce it is a custom field to change in the package.xml

I'm sorry about the changes between the metadata.js. It is my mistake, I had pull request on this files that I accepted and I did not propagate it. It definitely should be a sub module.

Did I answer your questions ?

**Comment by adamantine-dev** [comment]
Oh, I understood. It makes sense :)

Thank you!

**Comment by adamantine-dev** [comment]
Btw, what if I just added the new sObject to the Git - why the parsing doesn't work properly?

**Comment by scolladon** [comment]
Do you have an example ?

**Comment by adamantine-dev** [comment]
For example, I've started working on some task in a different branch. In a scope of the task, I have to create one custom sObject. I did it on Salesforce Setup. 

Then, I want to commit this new sObject to the Git repository. I did a retrieve of metadata and add the new sObject.xml file to local storage. From Git perspective it's like a creating the brand new XML file.

So, I have a branch with a few commits. The first commit (the last commit of the Master branch) has no the new sObject. The last commit of my branch has this new sObject (with fields, validation rules, record types, etc.)

The problem is your package doesn't parse deeply the new sObject.xml file. In the package.xml file I just see the _CustomObject_ type and thats all. There is no _CustomField_, _RecordType_, etc.

As I understood, you just handling the updating of existing sObject.xml files, like the adding the new fields or removing of them. But not the adding of the whole sObject.xml.

**Comment by scolladon** [comment]
Ahhh !

Yep ! You are absolutely right.
If I want to do it I will rely on the diff structure and the metadata structure sent by Salesforce (which both can change).

Else I should detect that I have an object, retrieve both from repo, translate them to json, compare them and write the diff package.xml. It's a lot of code and I do not have time right now :(

Plus, with the sfdx model, this use case do not exist anymore.
So, if no one ask it, I'm not sure I will do it
