### ISSUE TITLE
Issue with the parsing of aura components

### ISSUE THREAD

**Issue by adamantine-dev** [scolladon/sfdc-git-package#8]
I faced with the similar issue like this one: [Issue with the parsing of emails.](https://github.com/scolladon/sfdc-git-package/issues/7)

The package does delete all files inside the _aura_ folder.
Moreover, the _package.xml_ generates something interesting: it specified a name of a component and then after _'/'_ the name of a file.

Something like:

```xml
<members>MyComponent/MyComponentController</members>
<members>MyComponent/MyComponentHelper</members>
```

etc.

**Comment by scolladon** [comment]
fixed !
