### ISSUE TITLE
Package this project as an sfdx plugin

### ISSUE THREAD

**Issue by hicham-elmansouri** [scolladon/sfdc-git-package#9]
Hi Sebastian 
Very nice project. I m looking for a tool like this but something like an sfdx plugin. My idea is to pick up only diff and use sfdx:source:convert to generate the metadata. The only missing part is the destructive package.

What do you think about this approach? If this is something that your are interested in we can work together to build the plugin.

If it's not you can close the issue;-).

**Comment by scolladon** [comment]
Hi @hicham-elmansouri 
That is actually a great idea ! 
I thought to migrate this project as a plugin for sfdx a few months ago
If we are several ones to want I will do it :)
Maybe in september

**Comment by hicham-elmansouri** [comment]
Good let me know. Really excited and interested to be a part of this ;-)...

**Comment by scolladon** [comment]
the new project is created [here](https://github.com/scolladon/sfdx-git-package)
I'll work on it when I'll have time

**Comment by hicham-elmansouri** [comment]
Excellent. Can add you add me as a contributor?
